//Login
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT = 'LOGOUT';
export const AUTH_ERROR = 'AUTH_ERROR';

// Booking action types
export const GET_BOOKINGS_REQUEST = 'GET_BOOKINGS_REQUEST';
export const GET_BOOKINGS_SUCCESS = 'GET_BOOKINGS_SUCCESS';
export const GET_BOOKINGS_FAIL = 'GET_BOOKINGS_FAIL';


// Apartment action types
export const GET_APARTMENTS_REQUEST = 'GET_APARTMENTS_REQUEST';
export const GET_APARTMENTS_SUCCESS = 'GET_APARTMENTS_SUCCESS';
export const GET_APARTMENTS_FAIL = 'GET_APARTMENTS_FAIL';

export const GET_APARTMENT_REQUEST = 'GET_APARTMENT_REQUEST';
export const GET_APARTMENT_SUCCESS = 'GET_APARTMENT_SUCCESS';
export const GET_APARTMENT_FAIL = 'GET_APARTMENT_FAIL';

export const CREATE_APARTMENT_REQUEST = 'CREATE_APARTMENT_REQUEST';
export const CREATE_APARTMENT_SUCCESS = 'CREATE_APARTMENT_SUCCESS';
export const CREATE_APARTMENT_FAIL = 'CREATE_APARTMENT_FAIL';

export const UPDATE_APARTMENT_REQUEST = 'UPDATE_APARTMENT_REQUEST';
export const UPDATE_APARTMENT_SUCCESS = 'UPDATE_APARTMENT_SUCCESS';
export const UPDATE_APARTMENT_FAIL = 'UPDATE_APARTMENT_FAIL';

export const DELETE_APARTMENT_REQUEST = 'DELETE_APARTMENT_REQUEST';
export const DELETE_APARTMENT_SUCCESS = 'DELETE_APARTMENT_SUCCESS';
export const DELETE_APARTMENT_FAIL = 'DELETE_APARTMENT_FAIL';


// store/types/guestTypes.js
export const GET_GUESTS_REQUEST = 'GET_GUESTS_REQUEST';
export const GET_GUESTS_SUCCESS = 'GET_GUESTS_SUCCESS';
export const GET_GUESTS_FAIL = 'GET_GUESTS_FAIL';

export const UPDATE_GUEST_REQUEST = 'UPDATE_GUEST_REQUEST';
export const UPDATE_GUEST_SUCCESS = 'UPDATE_GUEST_SUCCESS';
export const UPDATE_GUEST_FAIL = 'UPDATE_GUEST_FAIL';

//inventory types
export const GET_PRODUCTS_REQUEST = 'GET_PRODUCTS_REQUEST';
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const GET_PRODUCTS_FAIL = 'GET_PRODUCTS_FAIL';

export const ADD_PRODUCT_SUCCESS = 'ADD_PRODUCT_SUCCESS';
export const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS';
export const UPDATE_PRODUCT_SUCCESS = 'UPDATE_PRODUCT_SUCCESS';

//stock types
export const STOCK_REMOVE_REQUEST = 'STOCK_REMOVE_REQUEST';
export const STOCK_REMOVE_SUCCESS = 'STOCK_REMOVE_SUCCESS';
export const STOCK_REMOVE_FAIL = 'STOCK_REMOVE_FAIL';

export const GET_STOCK_LOGS_REQUEST = 'GET_STOCK_LOGS_REQUEST';
export const GET_STOCK_LOGS_SUCCESS = 'GET_STOCK_LOGS_SUCCESS';
export const GET_STOCK_LOGS_FAIL = 'GET_STOCK_LOGS_FAIL';

//expenses
export const GET_EXPENSES_REQUEST = 'GET_EXPENSES_REQUEST';
export const GET_EXPENSES_SUCCESS = 'GET_EXPENSES_SUCCESS';
export const GET_EXPENSES_FAIL = 'GET_EXPENSES_FAIL';

export const ADD_EXPENSE_SUCCESS = 'ADD_EXPENSE_SUCCESS';
export const DELETE_EXPENSE_SUCCESS = 'DELETE_EXPENSE_SUCCESS';
export const UPDATE_EXPENSE_SUCCESS = 'UPDATE_EXPENSE_SUCCESS';


///////////////dashboard/////////////////////

//booking dashboard
export const GET_TOTAL_BOOKINGS_REQUEST = 'GET_TOTAL_BOOKINGS_REQUEST';
export const GET_TOTAL_BOOKINGS_SUCCESS = 'GET_TOTAL_BOOKINGS_SUCCESS';
export const GET_TOTAL_BOOKINGS_FAIL = 'GET_TOTAL_BOOKINGS_FAIL';

//total revenue
export const GET_TOTAL_REVENUE_REQUEST = 'GET_TOTAL_REVENUE_REQUEST';
export const GET_TOTAL_REVENUE_SUCCESS = 'GET_TOTAL_REVENUE_SUCCESS';
export const GET_TOTAL_REVENUE_FAIL = 'GET_TOTAL_REVENUE_FAIL';

// average length stay
export const GET_AVG_LENGTH_STAY_REQUEST = 'GET_AVG_LENGTH_STAY_REQUEST';
export const GET_AVG_LENGTH_STAY_SUCCESS = 'GET_AVG_LENGTH_STAY_SUCCESS';
export const GET_AVG_LENGTH_STAY_FAIL = 'GET_AVG_LENGTH_STAY_FAIL';

//repeat guest
export const GET_REPEAT_GUESTS_REQUEST = 'GET_REPEAT_GUESTS_REQUEST';
export const GET_REPEAT_GUESTS_SUCCESS = 'GET_REPEAT_GUESTS_SUCCESS';
export const GET_REPEAT_GUESTS_FAIL = 'GET_REPEAT_GUESTS_FAIL';

//revenue per apartment
export const GET_REVENUE_PER_APARTMENT_REQUEST = 'GET_REVENUE_PER_APARTMENT_REQUEST';
export const GET_REVENUE_PER_APARTMENT_SUCCESS = 'GET_REVENUE_PER_APARTMENT_SUCCESS';
export const GET_REVENUE_PER_APARTMENT_FAIL = 'GET_REVENUE_PER_APARTMENT_FAIL';


//top 5 products sold
export const GET_TOP_PRODUCTS_REQUEST = 'GET_TOP_PRODUCTS_REQUEST';
export const GET_TOP_PRODUCTS_SUCCESS = 'GET_TOP_PRODUCTS_SUCCESS';
export const GET_TOP_PRODUCTS_FAIL = 'GET_TOP_PRODUCTS_FAIL';

//low on product stock
export const GET_LOW_STOCK_REQUEST = 'GET_LOW_STOCK_REQUEST';
export const GET_LOW_STOCK_SUCCESS = 'GET_LOW_STOCK_SUCCESS';
export const GET_LOW_STOCK_FAIL = 'GET_LOW_STOCK_FAIL';

//all expenses
export const GET_TOTAL_EXPENSES_REQUEST = 'GET_TOTAL_EXPENSES_REQUEST';
export const GET_TOTAL_EXPENSES_SUCCESS = 'GET_TOTAL_EXPENSES_SUCCESS';
export const GET_TOTAL_EXPENSES_FAILURE = 'GET_TOTAL_EXPENSES_FAILURE';